permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: PROD frontend

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'     
        required: true
        default: 'prod'
        options: ['prod']
        type: choice
      region:
        description: 'Region'     
        required: true
        default: 'eu-central-1'
        options: ['eu-central-1']
        type: choice

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        #role-to-assume: arn:aws:iam::622157788797:role/github_role
        role-to-assume: arn:aws:iam::539016438966:role/github_role
        role-duration-seconds: 900 # the ttl of the session, in seconds.	
        aws-region: ${{ github.event.inputs.region }}

    - name: Deploy static site to S3 bucket
      # use different bucket for dev and prod. use input variables to the workflow to dynamically name the s3.
      # can s3 bucket be created via terraform if not already present
      run: aws s3 sync ./frontend/ s3://static-web-hosting-cp --delete
      
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: "E26GICS88INVC1"
        PATHS: "/*"
        AWS-REGION: ${{ github.event.inputs.region }}
